apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: clothesstore-dev

resources:
  - ../../base
  - namespace.yaml
  - quota.yaml

patches:
  - path: patches/web-image.yaml
  - path: patches/web-resources.yaml
  - path: patches/web-replicas.yaml
  - path: patches/postgres-resources.yaml
  - path: patches/web-strategy.yaml
