apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: clothesstore-dev

resources:
  - ../../base
  - namespace.yaml
  - quota.yaml
  - debug-pod.yaml

patchesStrategicMerge:
  - patches/web-image.yaml
  - patches/web-resources.yaml
  - patches/web-replicas.yaml
