apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: verticalpodautoscalers.autoscaling.k8s.io
  annotations:
    api-approved.kubernetes.io: "https://github.com/kubernetes/kubernetes/pull/63797"
spec:
  group: autoscaling.k8s.io
  names:
    kind: VerticalPodAutoscaler
    listKind: VerticalPodAutoscalerList
    plural: verticalpodautoscalers
    shortNames:
      - vpa
    singular: verticalpodautoscaler
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - description: The current update policy of the VPA object.
          jsonPath: .spec.updatePolicy.updateMode
          name: Mode
          type: string
        - description: Minimum resources recommended by this VPA.
          jsonPath: .status.recommendation.containerRecommendations[0].lowerBound.cpu
          name: CPU
          type: string
        - description: Minimum resources recommended by this VPA.
          jsonPath: .status.recommendation.containerRecommendations[0].lowerBound.memory
          name: Mem
          type: string
        - description: Whether the recommendation is provided.
          jsonPath: .status.conditions[?(@.type=="RecommendationProvided")].status
          name: Provided
          type: string
      name: v1
      schema:
        openAPIV3Schema:
          description: VerticalPodAutoscaler is the configuration for a VPA resource.
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              properties:
                resourcePolicy:
                  properties:
                    containerPolicies:
                      items:
                        properties:
                          containerName:
                            type: string
                          controlledResources:
                            items:
                              type: string
                            type: array
                          controlledValues:
                            enum:
                              - RequestsAndLimits
                              - RequestsOnly
                            type: string
                          maxAllowed:
                            additionalProperties:
                              anyOf:
                                - type: integer
                                - type: string
                              x-kubernetes-int-or-string: true
                            type: object
                          minAllowed:
                            additionalProperties:
                              anyOf:
                                - type: integer
                                - type: string
                              x-kubernetes-int-or-string: true
                            type: object
                          mode:
                            enum:
                              - Auto
                              - "Off"
                            type: string
                        type: object
                      type: array
                  type: object
                targetRef:
                  description: Reference to the controller managing the set of pods for the VPA.
                  properties:
                    apiVersion:
                      type: string
                    kind:
                      type: string
                    name:
                      type: string
                  type: object
                updatePolicy:
                  properties:
                    updateMode:
                      enum:
                        - "Off"
                        - Initial
                        - Recreate
                        - Auto
                      type: string
                  type: object
              required:
                - targetRef
              type: object
            status:
              properties:
                conditions:
                  items:
                    properties:
                      lastTransitionTime:
                        format: date-time
                        type: string
                      message:
                        type: string
                      reason:
                        type: string
                      status:
                        type: string
                      type:
                        type: string
                    required:
                      - status
                      - type
                    type: object
                  type: array
                recommendation:
                  properties:
                    containerRecommendations:
                      items:
                        properties:
                          containerName:
                            type: string
                          lowerBound:
                            additionalProperties:
                              anyOf:
                                - type: integer
                                - type: string
                              x-kubernetes-int-or-string: true
                            type: object
                          target:
                            additionalProperties:
                              anyOf:
                                - type: integer
                                - type: string
                              x-kubernetes-int-or-string: true
                            type: object
                          uncappedTarget:
                            additionalProperties:
                              anyOf:
                                - type: integer
                                - type: string
                              x-kubernetes-int-or-string: true
                            type: object
                          upperBound:
                            additionalProperties:
                              anyOf:
                                - type: integer
                                - type: string
                              x-kubernetes-int-or-string: true
                            type: object
                        required:
                          - containerName
                          - lowerBound
                          - target
                          - uncappedTarget
                          - upperBound
                        type: object
                      type: array
                  type: object
              type: object
          required:
            - spec
          type: object
      served: true
      storage: true
      subresources:
        status: {}

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: verticalpodautoscalercheckpoints.autoscaling.k8s.io
  annotations:
    api-approved.kubernetes.io: "https://github.com/kubernetes/kubernetes/pull/63797"
spec:
  group: autoscaling.k8s.io
  names:
    kind: VerticalPodAutoscalerCheckpoint
    listKind: VerticalPodAutoscalerCheckpointList
    plural: verticalpodautoscalercheckpoints
    singular: verticalpodautoscalercheckpoint
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              properties:
                containerName:
                  type: string
                vpaObjectName:
                  type: string
              required:
                - containerName
                - vpaObjectName
              type: object
            status:
              properties:
                lastUpdateTime:
                  format: date-time
                  type: string
                version:
                  type: string
              type: object
          required:
            - spec
          type: object
      served: true
      storage: true
      subresources:
        status: {}
