apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - web-deploy.yaml
  - web-svc.yaml
  - postgres-sts.yaml
  - postgres-svc.yaml
  - configmap.yaml
  - secret.yaml
  - limitrange.yaml
  - generated/db-init-sql.yaml
  - vpa-web.yaml
