apiVersion: v1
kind: Secret
metadata:
  name: clothesstore-secret
type: Opaque
stringData:
  DATABASE_URL: "postgres://postgres:admin@postgres:5432/estore"
  JWT_SECRET: "4dd16f226fe04bd6bf84143819ab1296"
