apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: clothesstore-prod

resources:
  - ../../base
  - namespace.yaml
  - hpa-web.yaml

patches:
  - path: patches/web-image.yaml
  - path: patches/web-resources.yaml
  - path: patches/web-replicas.yaml
